from portkey_ai.api_resources.instrumentation.models.tracing_config import (
    TracingConfig,
    ModuleConfig,
    ClassConfig,
    MethodConfig,
)


langchain_core_tracing_config = TracingConfig(
    name="langchain_core",
    min_version="0.2.0",
    modules=[
        ModuleConfig(
            name="langchain_core.language_models.chat_models",
            classes=[
                ClassConfig(
                    name="BaseChatModel",
                    methods=[
                        MethodConfig(name="invoke"),
                        MethodConfig(name="ainvoke"),
                        MethodConfig(name="stream"),
                        MethodConfig(name="astream"),
                        MethodConfig(name="generate"),
                        MethodConfig(name="agenerate"),
                        MethodConfig(name="generate_prompt"),
                        MethodConfig(name="agenerate_prompt"),
                        MethodConfig(name="bind_tools"),
                        MethodConfig(name="with_structured_output"),
                    ],
                )
            ],
        ),
        ModuleConfig(
            name="langchain_core.language_models.llms",
            classes=[
                ClassConfig(
                    name="BaseLLM",
                    methods=[
                        MethodConfig(name="invoke"),
                        MethodConfig(name="ainvoke"),
                        MethodConfig(name="batch"),
                        MethodConfig(name="abatch"),
                        MethodConfig(name="stream"),
                        MethodConfig(name="astream"),
                        MethodConfig(name="generate"),
                        MethodConfig(name="agenerate"),
                        MethodConfig(name="generate_prompt"),
                        MethodConfig(name="agenerate_prompt"),
                    ],
                )
            ],
        ),
        ModuleConfig(
            name="langchain_core.retrievers",
            classes=[
                ClassConfig(
                    name="BaseRetriever",
                    methods=[
                        MethodConfig(name="invoke"),
                        MethodConfig(name="ainvoke"),
                    ],
                )
            ],
        ),
        ModuleConfig(
            name="langchain_core.prompts.chat",
            classes=[
                ClassConfig(
                    name="BaseChatPromptTemplate",
                    methods=[
                        MethodConfig(name="format"),
                        MethodConfig(name="aformat"),
                        MethodConfig(name="format_prompt"),
                        MethodConfig(name="aformat_prompt"),
                        MethodConfig(name="format_messages"),
                        MethodConfig(name="aformat_messages"),
                    ],
                ),
                ClassConfig(
                    name="ChatPromptTemplate",
                    methods=[
                        MethodConfig(name="validate_input_variables"),
                        MethodConfig(name="from_template"),
                        MethodConfig(name="from_messages"),
                        MethodConfig(name="format_messages"),
                        MethodConfig(name="partial"),
                        MethodConfig(name="append"),
                        MethodConfig(name="extend"),
                    ],
                ),
            ],
        ),
        ModuleConfig(
            name="langchain_core.runnables.base",
            classes=[
                ClassConfig(
                    name="RunnableSequence",
                    methods=[
                        MethodConfig(name="invoke"),
                        MethodConfig(name="ainvoke"),
                        MethodConfig(name="as_tool"),
                        MethodConfig(name="assign"),
                        MethodConfig(name="astream"),
                        MethodConfig(name="astream_events"),
                        MethodConfig(name="astream_log"),
                        MethodConfig(name="atransform"),
                        MethodConfig(name="abatch"),
                        MethodConfig(name="abatch_as_completed"),
                        MethodConfig(name="batch"),
                        MethodConfig(name="batch_as_completed"),
                        MethodConfig(name="bind"),
                        MethodConfig(name="configurable_alternatives"),
                        MethodConfig(name="configurable_fields"),
                        MethodConfig(name="config_schema"),
                        MethodConfig(name="get_config_jsonschema"),
                        MethodConfig(name="get_graph"),
                        MethodConfig(name="get_input_jsonschema"),
                        MethodConfig(name="get_input_schema"),
                        MethodConfig(name="get_lc_namespace"),
                        MethodConfig(name="get_name"),
                        MethodConfig(name="get_output_jsonschema"),
                        MethodConfig(name="get_output_schema"),
                        MethodConfig(name="get_prompts"),
                        MethodConfig(name="is_lc_serializable"),
                        MethodConfig(name="invoke"),
                        MethodConfig(name="map"),
                        MethodConfig(name="pipe"),
                        MethodConfig(name="pick"),
                        MethodConfig(name="stream"),
                        MethodConfig(name="to_json"),
                        MethodConfig(name="transform"),
                        MethodConfig(name="with_alisteners"),
                        MethodConfig(name="with_config"),
                        MethodConfig(name="with_fallbacks"),
                        MethodConfig(name="with_listeners"),
                        MethodConfig(name="with_retry"),
                        MethodConfig(name="with_types"),
                    ],
                ),
                ClassConfig(
                    name="RunnableParallel",
                    methods=[
                        MethodConfig(name="invoke"),
                        MethodConfig(name="ainvoke"),
                        MethodConfig(name="as_tool"),
                        MethodConfig(name="assign"),
                        MethodConfig(name="astream"),
                        MethodConfig(name="astream_events"),
                        MethodConfig(name="astream_log"),
                        MethodConfig(name="atransform"),
                        MethodConfig(name="abatch"),
                        MethodConfig(name="abatch_as_completed"),
                        MethodConfig(name="batch"),
                        MethodConfig(name="batch_as_completed"),
                        MethodConfig(name="bind"),
                        MethodConfig(name="configurable_alternatives"),
                        MethodConfig(name="configurable_fields"),
                        MethodConfig(name="config_schema"),
                        MethodConfig(name="get_config_jsonschema"),
                        MethodConfig(name="get_graph"),
                        MethodConfig(name="get_input_jsonschema"),
                        MethodConfig(name="get_input_schema"),
                        MethodConfig(name="get_lc_namespace"),
                        MethodConfig(name="get_name"),
                        MethodConfig(name="get_output_jsonschema"),
                        MethodConfig(name="get_output_schema"),
                        MethodConfig(name="get_prompts"),
                        MethodConfig(name="is_lc_serializable"),
                        MethodConfig(name="invoke"),
                        MethodConfig(name="map"),
                        MethodConfig(name="pipe"),
                        MethodConfig(name="pick"),
                        MethodConfig(name="stream"),
                        MethodConfig(name="to_json"),
                        MethodConfig(name="transform"),
                        MethodConfig(name="with_alisteners"),
                        MethodConfig(name="with_config"),
                        MethodConfig(name="with_fallbacks"),
                        MethodConfig(name="with_listeners"),
                        MethodConfig(name="with_retry"),
                        MethodConfig(name="with_types"),
                    ],
                ),
                ClassConfig(
                    name="RunnableLambda",
                    methods=[
                        MethodConfig(name="invoke"),
                        MethodConfig(name="ainvoke"),
                        MethodConfig(name="as_tool"),
                        MethodConfig(name="assign"),
                        MethodConfig(name="astream"),
                        MethodConfig(name="astream_events"),
                        MethodConfig(name="astream_log"),
                        MethodConfig(name="atransform"),
                        MethodConfig(name="abatch"),
                        MethodConfig(name="abatch_as_completed"),
                        MethodConfig(name="batch"),
                        MethodConfig(name="batch_as_completed"),
                        MethodConfig(name="bind"),
                        MethodConfig(name="config_schema"),
                        MethodConfig(name="get_config_jsonschema"),
                        MethodConfig(name="get_graph"),
                        MethodConfig(name="get_input_jsonschema"),
                        MethodConfig(name="get_input_schema"),
                        MethodConfig(name="get_name"),
                        MethodConfig(name="get_output_jsonschema"),
                        MethodConfig(name="get_output_schema"),
                        MethodConfig(name="get_prompts"),
                        MethodConfig(name="invoke"),
                        MethodConfig(name="map"),
                        MethodConfig(name="pipe"),
                        MethodConfig(name="pick"),
                        MethodConfig(name="stream"),
                        MethodConfig(name="transform"),
                        MethodConfig(name="with_alisteners"),
                        MethodConfig(name="with_config"),
                        MethodConfig(name="with_fallbacks"),
                        MethodConfig(name="with_listeners"),
                        MethodConfig(name="with_retry"),
                        MethodConfig(name="with_types"),
                    ],
                ),
            ],
        ),
        ModuleConfig(
            name="langchain_core.runnables.passthrough",
            classes=[
                ClassConfig(
                    pattern=".*",
                    methods=[
                        MethodConfig(name="invoke"),
                        MethodConfig(name="ainvoke"),
                        MethodConfig(name="transform"),
                        MethodConfig(name="atransform"),
                        MethodConfig(name="stream"),
                        MethodConfig(name="astream"),
                    ],
                )
            ],
        ),
        ModuleConfig(
            name="langchain_core.output_parsers.string",
            classes=[ClassConfig(pattern=".*", methods=[MethodConfig(name="parse")])],
        ),
        ModuleConfig(
            name="langchain_core.output_parsers.json",
            classes=[
                ClassConfig(
                    pattern=".*",
                    methods=[
                        MethodConfig(name="parse"),
                        MethodConfig(name="parse_result"),
                        MethodConfig(name="get_format_instructions"),
                    ],
                )
            ],
        ),
        ModuleConfig(
            name="langchain_core.output_parsers.list",
            classes=[
                ClassConfig(
                    pattern=".*",
                    methods=[
                        MethodConfig(name="parse"),
                        MethodConfig(name="parse_iter"),
                    ],
                )
            ],
        ),
        ModuleConfig(
            name="langchain_core.output_parsers.xml",
            classes=[
                ClassConfig(
                    pattern=".*",
                    methods=[
                        MethodConfig(name="parse"),
                        MethodConfig(name="parse_iter"),
                    ],
                )
            ],
        ),
    ],
)
